services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - BYBIT_API_KEY=${BYBIT_API_KEY}
      - BYBIT_API_SECRET=${BYBIT_API_SECRET}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    depends_on:
      - redis
    volumes:
      - ./bot.log:/app/bot.log
      - ./lstm_model.pth:/app/lstm_model.pth
    networks:
      - bot-net
  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    networks:
      - bot-net
networks:
  bot-net:
    driver: bridge